### PR TITLE
Introduce handpick

### PR DESCRIPTION
**Pull request by redaxmedia**
Hey,

not 100% sure this fits perfect into your list but with [handpick](https://github.com/redaxmedia/handpick) you can manage Node dependencies easier. The original idea behind this project was to speed up CI pipelines by installing a fragment of devDependencies:

Terminal Session

Whatsoever, I have seen usecases in monorepos that utilize frontendDependencies and backendDependencies and therefore suggest this project to be added.

Best regards
Henry

### CODE REVIEW

**Comment by korfuri** [comment]
Hey, sorry for the slow response - I took a look at handpick but I don't understand what it does exactly. I am not familiar with JS dependency management enough, maybe. Can you make a one-sentence description of why this helps maange a monorepo, for people who don't already know the tool? Thanks!

**Comment by redaxmedia** [comment]
@korfuri A `package.json` and therefore NPM, YARN and PNPM do have pretty limited support for the type of dependencies, it official supports `dependencies` and `devDependencies` out of the box. With handpick you can define unsupported types of dependencies that are related to a task like linting, testing, building or related to a workspace.

**Comment by redaxmedia** [comment]
@korfuri It has been a while...

**Comment by korfuri** [comment]
Thanks for the explanation. Can you change the description in the README.md to be more explicit?
* Mention that this targets Javascript only;
* Mention that this is a dependency management tool that allows the user to define various dependency sets for different use-cases;
In one sentence. E.g. "handpick is a dependency management tool for Javascript monorepos with support for distinct dependency sets for different use-cases"

I'd do it but I don't have commit rights to your PR branch and I'm not sure my formulation is precise enough. Thanks!

**Comment by redaxmedia** [comment]
I deleted my fork already and cannot do that...  could you still merge that one and change the description? Or let me send another PR afterwards...

**Comment by redaxmedia** [comment]
Closing this now... I actually have enough fooling around for half a year.

**Pull request closed without merging**
